import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import worker,{assess,validateAssessment} from './worker.mjs';
const good={speechDetected:true,feedback:'Try the long aa sound.',heard:'आ'};
for(const score of [0,1,4])assert.equal(validateAssessment({...good,score}).passed,false);
for(const score of [5,6,10])assert.equal(validateAssessment({...good,score}).passed,true);
assert.equal(validateAssessment({...good,score:10,speechDetected:false}).score,0);
for(const score of [-1,11,NaN,'6',5.5])assert.throws(()=>validateAssessment({...good,score}));
const wav=new Uint8Array(44+32000),v=new DataView(wav.buffer),text=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));};
text(0,'RIFF');v.setUint32(4,wav.length-8,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);text(36,'data');v.setUint32(40,32000,true);
const request=(options={})=>new Request('https://marathi-mitra-learning.mai3yee.chatgpt.site/api/assess-pronunciation?target=word-1',{method:'POST',headers:{origin:'https://marathi-mitra-learning.mai3yee.chatgpt.site','oai-authenticated-user-id':'test-user',...options.headers},body:options.body||wav});
let calls=0;
const mock=score=>async (url,options)=>{calls++;assert.equal(url,'https://api.openai.com/v1/chat/completions');const payload=JSON.parse(options.body);assert.equal(payload.store,false);assert.equal(payload.messages[1].content.filter(x=>x.type==='input_audio').length,2);return Response.json({choices:[{message:{content:JSON.stringify({...good,score})}}]});};
assert.equal((await assess(request(),{})).status,503);assert.equal(calls,0);
assert.equal((await assess(request({headers:{'oai-authenticated-user-id':''}}),{OPENAI_API_KEY:'test'})).status,401);
assert.equal((await assess(request({headers:{origin:'https://wrong.test'}}),{OPENAI_API_KEY:'test'})).status,403);
assert.equal((await assess(request({body:'invalid'}),{OPENAI_API_KEY:'test'})).status,400);
for(const score of [4,5,8]){const result=await (await assess(request(),{OPENAI_API_KEY:'test'},mock(score))).json();assert.equal(result.score,score);assert.equal(result.passed,score>=5);}
assert.equal((await assess(request(),{OPENAI_API_KEY:'test'},mock(11))).status,502);
const status=await (await worker.fetch(new Request('https://example.test/api/scoring-status'),{})).json();assert.equal(status.available,false);
assert.equal((await worker.fetch(new Request('https://example.test/'),{})).status,200);
assert.equal((await worker.fetch(new Request('https://example.test/audio/word-1.mp3'),{})).headers.get('content-type'),'audio/mpeg');
const ui={button:{},result:{textContent:'',className:''},continueButton:{},target:'word-1'};
const context=vm.createContext({window:{},fetch:async()=>Response.json({available:false}),AbortController,console,setTimeout,clearTimeout});
vm.runInContext(fs.readFileSync('dist/scoring.js','utf8'),context);
const gate=context.window.createPronunciationAssessment(ui);assert.equal(ui.continueButton.disabled,true);assert.equal(gate.canContinue(),false);
assert.equal(context.window.isPassingPronunciation(4),false);assert.equal(context.window.isPassingPronunciation(5),true);assert.equal(context.window.isPassingPronunciation(6),true);
gate.recordingReady(new Blob(['recording']));assert.equal(ui.button.disabled,false);assert.equal(ui.continueButton.disabled,true);gate.recordingStarted();assert.equal(ui.button.disabled,true);assert.equal(ui.continueButton.disabled,true);gate.dispose();
console.log('Pronunciation boundaries, no-service lock, malformed scores, endpoint auth, two-audio request, and UI gate passed. API responses were mocked; live scoring is unverified.');
